version: '3'

services:

  pg-ttd:
    image: bitnami/postgresql:latest
    container_name: pg-ttd
    tty: true
    volumes:
      - pgdata:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=ttd_database
    ports:
      - "5432:5432"

volumes:
  pgdata: